### ISSUE TITLE
yo man, everything okay

### ISSUE THREAD

**Issue by lupuleasa-core** [sbtoonz/sbtoonz#1]
I noticed the backpack mod repo is no longer there and that you are no longer in Odin discord

anything happened? you okay?

missing you already

**Comment by sbtoonz** [comment]
Was just better to leave than say something I might regret

**Comment by lupuleasa-core** [comment]
I understand

**Comment by sbtoonz** [comment]
feel free to friend me on discord ill still answer questions you might have about modding that other game you were interested in tinkering with
